# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
production:
  adapter: mysql
  database: text_umes_mb_ca
  host: localhost
  username: umesadmin
  password: umesL061N
  encoding: utf8
  socket: /tmp/mysql.sock


